// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqVxPN_4Y9H1EVWKUZW0TTBuzYQovq5c',
    appId: '1:397658475995:web:09196da7677c1b5084ebfe',
    messagingSenderId: '397658475995',
    projectId: 'flutter-login-app-4d1a2',
    authDomain: 'flutter-login-app-4d1a2.firebaseapp.com',
    databaseURL: 'https://flutter-login-app-4d1a2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-app-4d1a2.firebasestorage.app',
    measurementId: 'G-H93V1F7YT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHcSR4DcKlLRQ-aERJJGx7BdHJLhM91w',
    appId: '1:397658475995:android:e0beee1cb5b71e9b84ebfe',
    messagingSenderId: '397658475995',
    projectId: 'flutter-login-app-4d1a2',
    databaseURL: 'https://flutter-login-app-4d1a2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-app-4d1a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ZZ4kK33mS8cgZ8bKACKS6dL767RPuuA',
    appId: '1:397658475995:ios:3d90f473851156f984ebfe',
    messagingSenderId: '397658475995',
    projectId: 'flutter-login-app-4d1a2',
    databaseURL: 'https://flutter-login-app-4d1a2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-app-4d1a2.firebasestorage.app',
    androidClientId: '397658475995-4raajd8g1ki5k785n2reakd78qtb4t36.apps.googleusercontent.com',
    iosClientId: '397658475995-emdvv0p5meoga1t0q44p76scpc6au951.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpqVxPN_4Y9H1EVWKUZW0TTBuzYQovq5c',
    appId: '1:397658475995:web:228225458f4ae8ff84ebfe',
    messagingSenderId: '397658475995',
    projectId: 'flutter-login-app-4d1a2',
    authDomain: 'flutter-login-app-4d1a2.firebaseapp.com',
    databaseURL: 'https://flutter-login-app-4d1a2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-app-4d1a2.firebasestorage.app',
    measurementId: 'G-98VZ1V87RV',
  );

}